### PR TITLE
feat: implement sample_orientations_from_CTF workflow

### PR DESCRIPTION
**Pull request by gcapes**
I'm not sure if the `doc` string in the workflow is still ok, or needs updating?

### CODE REVIEW

**Comment by aplowman** [comment]
I think this is missing the corresponding MTEX script (`sample_orientations_CTF.m`) and demo workflow?

**Comment by gcapes** [comment]
Ah yes, looks like I amended the commit but never pushed it :facepalm:

**Review by aplowman — APPROVED** [review]

**Review by aplowman — CHANGES_REQUESTED** [review]
I forgot, could you also update the README table, to show this has now been implemented? Thanks!

**Comment by gcapes** [comment]
I've updated the README, but need to wait until this is merged to get the link to the docs. I've added a placeholder for now so it doesn't get forgotten.

**Review by aplowman — APPROVED** [review]

**Pull request merged**
